### ISSUE TITLE
nuxt warning

### ISSUE THREAD

**Issue by venturion** [LucasLeandro1204/vue-content-loading#10]
hi,
i have this warning using the plugin with nuxt:
You are using the runtime-only build of Vue where the template compiler is not available

the nuxt developer said thats a package error
you may delivery non built package

**Comment by LucasLeandro1204** [comment]
Hey, thank you for the advice, I will fix it when I get time, but feel free to open a pull request to solve this issue =)

**Comment by tatyshev** [comment]
@LucasLeandro1204 #11

**Comment by LucasLeandro1204** [comment]
@venturion Can you check now please? And thank you again @tatyshev
